In [6]:
import numpy as np
import time

In [7]:


start = time.time()
arr1 = np.array([1, 2, 3, 4, 5])
list_ans = arr1 ** 2
end = time.time()

rest = end - start
print("Squared Array:", list_ans)
print("Time taken:", rest)


Squared Array: [ 1  4  9 16 25]
Time taken: 0.0016560554504394531


In [10]:
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
arr2.shape

(3, 3)

In [13]:
arr2.astype('float64')

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [16]:
arr3=np.array([1,2,3,4,5,6])
idx=[1,3,5]
print(arr3[idx])

[2 4 6]


In [17]:
arr4=np.array([1,2,3,4,5,6,7,8,9])
arr4.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
arr5=np.array([[100,200,32],[78,87,97],[75,45,11]])
print(arr5[arr5>25])

[100 200  32  78  87  97  75  45]
